import static org.junit.Assert.*;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import excepciones.DAOExcepcion;
import excepciones.LogicaExcepcion;
import logica.Controlador;
import persistencia.ConnectionManager;
import presentacion.CrearAsesor;



/**
 * @author Pau Alario
 */

public class CrearAsesorTest_Bug594 {
	Controlador controlador;
    ConnectionManager conexion;
    String cod;
    String nombre;
    CrearAsesor asesor;
	

    @Before
    public void inicializar() {
    	controlador = Controlador.dameControlador();
        asesor = new CrearAsesor(controlador);
        cod="";
        nombre="";
    }
    
    @Test
    public void test() {
    	try{
            asesor.setCampos(cod,nombre);
            asesor.botonOk();
	    	fail("El método debería de haber fallado");
    	}
    	catch(LogicaExcepcion e){

    		assertTrue(true);
    	}
    	
    }
    
    @After
    public void after(){
    	try{
    		ConnectionManager connManager = new ConnectionManager("practicaFinal");
            connManager.connect();
            
            connManager.updateDB("delete from asesor where CODIGO_EMPLEADO='" + cod + "'");
            
            connManager.close();
    	}
    	catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    	
    	catch(DAOExcepcion ex){
    		ex.printStackTrace();    		
    	}
    }

}